### ISSUE TITLE
@id value must be an absolut IRI

### ISSUE THREAD

**Issue by bourgeoa** [frogcat/ttl2jsonld#4]
I encountered this issue when implementing `ttl2jsonld` to serialize jsonld in https://github.com/linkeddata/rdflib.js (see screens below)
Your app does a good job to create a compact jsonld output with relative links from a compact ttl.
rdflib produce compact ttl with relative links and collections `@list.`

Actually the only issue is when ttl contains `@prefix` with non abolute IRI, like `@prefix : <#>.` or `@prefix n: </#>.`
`@id` value accepts relative url without any problem.

I made a simple function to find non valid IRI in @context. Then rebuild any @id value and delete @context declaration.
A better solution would to make a PR.

```
  statementsToJsonld (sts) {
    // ttl2jsonld creates context keys for all ttl prefix
    // context keys must be full IRI
    function findId (itemObj) {
      if (itemObj['@id']) {
        const item = itemObj['@id'].split(':')
        if (keys[item[0]]) itemObj['@id'] = jsonldObj['@context'][item[0]] + item[1]
      }
      const itemValues = Object.values(itemObj)
      for (const i in itemValues) {
        if (typeof itemValues[i] !== 'string') { // @list contains array
          findId(itemValues[i])
        }
      }
    }

    const turtleDoc = this.statementsToN3(sts)
    const jsonldObj = ttl2jsonld.parse(turtleDoc)
    const context = jsonldObj['@context']
    const iri = /^[a-z](.*?):(.+?)/g // begin with a letter, contain : followed by at least one character
    const keys = Object.keys(context).filter(key => !context[key].match(iri))

    findId(jsonldObj)
    keys.map(key => { delete jsonldObj['@context'][key] })
    console.log(JSON.stringify(jsonldObj, null, 2))

    return JSON.stringify(jsonldObj, null, 2)
  }

```

![image](https://user-images.githubusercontent.com/2218470/210140285-264e8bf1-7867-4309-ba4d-12e196a17b95.png)

![image](https://user-images.githubusercontent.com/2218470/210140327-7c18a093-6a8c-4565-8cec-2f9c75a5271d.png)

**Comment by frogcat** [comment]
I am so sorry for not replying to you sooner.

I understood the problem and added new test case [test-issue-4](https://github.com/frogcat/ttl2jsonld/blob/master/test/test-issue-4.js) .
Currently, [ttl2jsonld.js](https://github.com/frogcat/ttl2jsonld/blob/master/ttl2jsonld.js) has been improved to pass test-issue-4.

Please try [demo](https://frogcat.github.io/ttl2jsonld/demo/) again.
And let me know if new test case is not suitable.

**Comment by bourgeoa** [comment]
Thanks this is perfect.

In test issue I would have also added a line `@prefix : <#>.`
The demo results seems perfect.

Waiting for the npm version.

**Comment by frogcat** [comment]
Thank you again, [Version 0.0.9](https://www.npmjs.com/package/@frogcat/ttl2jsonld) released.
